version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: script/kill_process.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: script/run_process.sh
      timeout: 300
      runas: ec2-user
