CREATE DATABASE IF NOT EXISTS project01_db;

ALTER DATABASE project01_db
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'project01_db'@'%' IDENTIFIED BY 'project01_db';

GRANT ALL PRIVILEGES ON project01_db.* TO 'project01_db'@'%';

FLUSH PRIVILEGES;
